/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { 
  Stethoscope, 
  Activity, 
  MapPin, 
  Info, 
  AlertTriangle, 
  ChevronRight, 
  Search, 
  RefreshCcw, 
  Download, 
  Heart, 
  Droplets, 
  Apple, 
  Dumbbell,
  Menu,
  X,
  Phone,
  Clock,
  CheckCircle2
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { analyzeSymptoms } from './services/gemini';
import { SymptomReport, AgeGroup, Gender, Hospital } from './types';

// Mock Hospital Data
const MOCK_HOSPITALS: Hospital[] = [
  { name: "Village Health Center", distance: "2.5 km", contact: "+91 98765 43210", location: "Main Road, North Village" },
  { name: "District Government Hospital", distance: "12 km", contact: "011-2345678", location: "City Center, District HQ" },
  { name: "Community Clinic", distance: "5 km", contact: "+91 87654 32109", location: "Near Post Office, East Sector" },
  { name: "Maternal & Child Care Unit", distance: "8 km", contact: "011-9876543", location: "Hospital Road, West Block" },
];

const HEALTH_TIPS = [
  { icon: Droplets, title: "Drink Clean Water", desc: "Always boil or filter your water before drinking to prevent stomach infections.", color: "text-blue-500" },
  { icon: Heart, title: "Maintain Hygiene", desc: "Wash hands with soap before eating and after using the toilet.", color: "text-red-500" },
  { icon: Apple, title: "Eat Balanced Food", desc: "Include green vegetables, fruits, and pulses in your daily meals.", color: "text-green-500" },
  { icon: Dumbbell, title: "Exercise Regularly", desc: "Walking for 30 minutes daily helps keep your heart and body strong.", color: "text-orange-500" },
];

export default function App() {
  const [activeTab, setActiveTab] = useState<'home' | 'checker' | 'tips' | 'hospitals'>('home');
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  
  // Form State
  const [ageGroup, setAgeGroup] = useState<AgeGroup>('Adult (19-50)');
  const [gender, setGender] = useState<Gender>('Male');
  const [location, setLocation] = useState('');
  const [symptoms, setSymptoms] = useState('');
  
  // Result State
  const [isLoading, setIsLoading] = useState(false);
  const [report, setReport] = useState<SymptomReport | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleAnalyze = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!symptoms.trim()) return;
    
    setIsLoading(true);
    setError(null);
    try {
      const result = await analyzeSymptoms(symptoms, ageGroup, gender, location);
      setReport(result);
    } catch (err) {
      setError("Something went wrong. Please try again.");
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleReset = () => {
    setSymptoms('');
    setReport(null);
    setError(null);
  };

  const handleSaveReport = () => {
    if (!report) return;
    const reportText = `
AI Health Symptom Checker Report
-------------------------------
Age Group: ${ageGroup}
Gender: ${gender}
Location: ${location || 'Not specified'}

Detected Symptoms:
${report.detectedSymptoms.map(s => `- ${s}`).join('\n')}

Possible Conditions:
${report.possibleConditions.map(c => `- ${c.name}: ${c.description}`).join('\n')}

Precautions:
${report.precautions.map(p => `- ${p}`).join('\n')}

When to See a Doctor:
${report.whenToSeeDoctor.map(w => `- ${w}`).join('\n')}

DISCLAIMER: This report is generated by AI for informational purposes only. 
It is NOT a replacement for professional medical advice.
    `;
    
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Health_Report_${new Date().toLocaleDateString()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 bg-white border-b border-slate-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            <div className="flex items-center gap-2 cursor-pointer" onClick={() => setActiveTab('home')}>
              <div className="bg-blue-600 p-2 rounded-lg">
                <Stethoscope className="text-white w-6 h-6" />
              </div>
              <span className="font-bold text-xl text-slate-800 hidden sm:block">AI Health Checker</span>
              <span className="font-bold text-lg text-slate-800 sm:hidden">AI Health</span>
            </div>
            
            {/* Desktop Nav */}
            <div className="hidden md:flex items-center gap-8">
              {['home', 'checker', 'tips', 'hospitals'].map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab as any)}
                  className={`capitalize font-medium transition-colors ${
                    activeTab === tab ? 'text-blue-600' : 'text-slate-500 hover:text-blue-600'
                  }`}
                >
                  {tab === 'checker' ? 'Symptom Checker' : tab === 'tips' ? 'Health Tips' : tab}
                </button>
              ))}
            </div>

            {/* Mobile Nav Toggle */}
            <div className="md:hidden">
              <button onClick={() => setIsMenuOpen(!isMenuOpen)} className="p-2 text-slate-600">
                {isMenuOpen ? <X /> : <Menu />}
              </button>
            </div>
          </div>
        </div>

        {/* Mobile Menu */}
        <AnimatePresence>
          {isMenuOpen && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="md:hidden bg-white border-t border-slate-100 overflow-hidden"
            >
              <div className="px-4 py-4 space-y-2">
                {['home', 'checker', 'tips', 'hospitals'].map((tab) => (
                  <button
                    key={tab}
                    onClick={() => {
                      setActiveTab(tab as any);
                      setIsMenuOpen(false);
                    }}
                    className={`block w-full text-left px-4 py-3 rounded-xl capitalize font-medium ${
                      activeTab === tab ? 'bg-blue-50 text-blue-600' : 'text-slate-600'
                    }`}
                  >
                    {tab === 'checker' ? 'Symptom Checker' : tab === 'tips' ? 'Health Tips' : tab}
                  </button>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </nav>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Home Section */}
        {activeTab === 'home' && (
          <div className="space-y-16">
            <section className="text-center py-12 md:py-20 bg-gradient-to-br from-blue-600 to-indigo-700 rounded-3xl text-white px-6 shadow-xl">
              <motion.h1 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-4xl md:text-6xl font-extrabold mb-6"
              >
                Check Your Symptoms Instantly
              </motion.h1>
              <motion.p 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="text-xl md:text-2xl text-blue-100 mb-10 max-w-3xl mx-auto"
              >
                Get quick health guidance using AI, specially designed for rural communities.
              </motion.p>
              <motion.button
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => setActiveTab('checker')}
                className="bg-white text-blue-600 px-8 py-4 rounded-full font-bold text-lg shadow-lg hover:bg-blue-50 transition-colors inline-flex items-center gap-2"
              >
                Start Symptom Check <ChevronRight className="w-5 h-5" />
              </motion.button>
            </section>

            <section className="grid md:grid-cols-3 gap-8">
              <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 text-center">
                <div className="bg-blue-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6">
                  <Activity className="text-blue-600 w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-3">1. Enter Symptoms</h3>
                <p className="text-slate-600">Tell us how you feel in simple words like fever, cough, or pain.</p>
              </div>
              <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 text-center">
                <div className="bg-indigo-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6">
                  <Search className="text-indigo-600 w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-3">2. AI Analyzes</h3>
                <p className="text-slate-600">Our smart system understands your symptoms and looks for patterns.</p>
              </div>
              <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 text-center">
                <div className="bg-emerald-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6">
                  <Info className="text-emerald-600 w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-3">3. Get Guidance</h3>
                <p className="text-slate-600">Receive basic health advice and know when to see a doctor.</p>
              </div>
            </section>

            <section className="bg-amber-50 border border-amber-200 p-6 rounded-2xl flex gap-4 items-start">
              <AlertTriangle className="text-amber-600 w-6 h-6 flex-shrink-0 mt-1" />
              <div>
                <h4 className="font-bold text-amber-900 mb-1">Medical Disclaimer</h4>
                <p className="text-amber-800">
                  This tool provides basic health information and should not replace professional medical consultation. 
                  In case of emergency, please visit the nearest hospital immediately.
                </p>
              </div>
            </section>
          </div>
        )}

        {/* Symptom Checker Section */}
        {activeTab === 'checker' && (
          <div className="max-w-4xl mx-auto">
            <div className="mb-8">
              <h2 className="text-3xl font-bold text-slate-800 mb-2">Symptom Checker</h2>
              <p className="text-slate-600">Please provide accurate details for better guidance.</p>
            </div>

            <div className="grid lg:grid-cols-5 gap-8">
              <div className="lg:col-span-2 space-y-6">
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                  <h3 className="font-bold text-lg mb-4 flex items-center gap-2">
                    <Info className="w-5 h-5 text-blue-600" /> User Information
                  </h3>
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-700 mb-1">Age Group</label>
                      <select 
                        value={ageGroup}
                        onChange={(e) => setAgeGroup(e.target.value as AgeGroup)}
                        className="w-full p-3 rounded-xl border border-slate-200 focus:ring-2 focus:ring-blue-500 outline-none"
                      >
                        <option>Child (0-12)</option>
                        <option>Teen (13-18)</option>
                        <option>Adult (19-50)</option>
                        <option>Senior (50+)</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-700 mb-1">Gender</label>
                      <select 
                        value={gender}
                        onChange={(e) => setGender(e.target.value as Gender)}
                        className="w-full p-3 rounded-xl border border-slate-200 focus:ring-2 focus:ring-blue-500 outline-none"
                      >
                        <option>Male</option>
                        <option>Female</option>
                        <option>Prefer not to say</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-700 mb-1">City / Village</label>
                      <input 
                        type="text"
                        value={location}
                        onChange={(e) => setLocation(e.target.value)}
                        placeholder="Enter your location"
                        className="w-full p-3 rounded-xl border border-slate-200 focus:ring-2 focus:ring-blue-500 outline-none"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div className="lg:col-span-3 space-y-6">
                <form onSubmit={handleAnalyze} className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                  <h3 className="font-bold text-lg mb-4 flex items-center gap-2">
                    <Activity className="w-5 h-5 text-blue-600" /> Describe Symptoms
                  </h3>
                  <textarea 
                    value={symptoms}
                    onChange={(e) => setSymptoms(e.target.value)}
                    placeholder="Example: I have had a high fever for 2 days, a dry cough, and I feel very tired."
                    className="w-full h-40 p-4 rounded-xl border border-slate-200 focus:ring-2 focus:ring-blue-500 outline-none resize-none mb-4"
                    required
                  />
                  <div className="flex gap-3">
                    <button 
                      type="submit"
                      disabled={isLoading}
                      className="flex-1 bg-blue-600 text-white py-4 rounded-xl font-bold hover:bg-blue-700 transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
                    >
                      {isLoading ? (
                        <>
                          <RefreshCcw className="w-5 h-5 animate-spin" /> Analyzing...
                        </>
                      ) : (
                        'Analyze Symptoms'
                      )}
                    </button>
                    <button 
                      type="button"
                      onClick={handleReset}
                      className="p-4 rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-50 transition-colors"
                    >
                      <RefreshCcw className="w-5 h-5" />
                    </button>
                  </div>
                </form>

                {error && (
                  <div className="bg-red-50 border border-red-100 p-4 rounded-xl text-red-600 text-sm">
                    {error}
                  </div>
                )}

                <AnimatePresence>
                  {report && (
                    <motion.div 
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="space-y-6"
                    >
                      <div className="bg-white p-8 rounded-2xl shadow-md border border-blue-100 relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-4">
                          <button 
                            onClick={handleSaveReport}
                            className="flex items-center gap-2 text-blue-600 font-medium hover:underline"
                          >
                            <Download className="w-4 h-4" /> Save Report
                          </button>
                        </div>
                        
                        <h3 className="text-2xl font-bold text-slate-800 mb-8">Health Report</h3>
                        
                        <div className="grid md:grid-cols-2 gap-8">
                          <section>
                            <h4 className="font-bold text-blue-700 mb-4 flex items-center gap-2">
                              <CheckCircle2 className="w-5 h-5" /> Detected Symptoms
                            </h4>
                            <ul className="space-y-2">
                              {report.detectedSymptoms.map((s, i) => (
                                <li key={i} className="flex items-center gap-2 text-slate-700 bg-slate-50 p-2 rounded-lg">
                                  <div className="w-1.5 h-1.5 bg-blue-400 rounded-full" /> {s}
                                </li>
                              ))}
                            </ul>
                          </section>

                          <section>
                            <h4 className="font-bold text-indigo-700 mb-4 flex items-center gap-2">
                              <Activity className="w-5 h-5" /> Possible Conditions
                            </h4>
                            <div className="space-y-4">
                              {report.possibleConditions.map((c, i) => (
                                <div key={i} className="bg-indigo-50 p-3 rounded-xl border border-indigo-100">
                                  <p className="font-bold text-indigo-900">{c.name}</p>
                                  <p className="text-sm text-indigo-800">{c.description}</p>
                                </div>
                              ))}
                            </div>
                          </section>

                          <section>
                            <h4 className="font-bold text-emerald-700 mb-4 flex items-center gap-2">
                              <Heart className="w-5 h-5" /> Recommended Precautions
                            </h4>
                            <ul className="space-y-2">
                              {report.precautions.map((p, i) => (
                                <li key={i} className="flex items-start gap-2 text-slate-700">
                                  <ChevronRight className="w-4 h-4 text-emerald-500 mt-1 flex-shrink-0" /> {p}
                                </li>
                              ))}
                            </ul>
                          </section>

                          <section>
                            <h4 className="font-bold text-red-700 mb-4 flex items-center gap-2">
                              <AlertTriangle className="w-5 h-5" /> When to See a Doctor
                            </h4>
                            <ul className="space-y-2">
                              {report.whenToSeeDoctor.map((w, i) => (
                                <li key={i} className="flex items-start gap-2 text-red-800 bg-red-50 p-2 rounded-lg text-sm">
                                  <AlertTriangle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" /> {w}
                                </li>
                              ))}
                            </ul>
                          </section>
                        </div>

                        <div className="mt-10 pt-6 border-t border-slate-100 text-center">
                          <p className="text-xs text-slate-400 italic">
                            Disclaimer: This report is generated by AI for informational purposes only. 
                            It is NOT a replacement for professional medical advice.
                          </p>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>
          </div>
        )}

        {/* Health Tips Section */}
        {activeTab === 'tips' && (
          <div className="max-w-4xl mx-auto">
            <div className="mb-12 text-center">
              <h2 className="text-3xl font-bold text-slate-800 mb-4">Daily Health Tips</h2>
              <p className="text-slate-600">Simple habits to keep you and your family healthy.</p>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              {HEALTH_TIPS.map((tip, i) => (
                <motion.div 
                  key={i}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 flex gap-6 items-start"
                >
                  <div className={`p-4 rounded-2xl bg-slate-50 ${tip.color}`}>
                    <tip.icon className="w-8 h-8" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold mb-2">{tip.title}</h3>
                    <p className="text-slate-600 leading-relaxed">{tip.desc}</p>
                  </div>
                </motion.div>
              ))}
            </div>

            <div className="mt-12 bg-blue-600 rounded-3xl p-8 text-white text-center">
              <h3 className="text-2xl font-bold mb-4">Stay Healthy, Stay Happy</h3>
              <p className="text-blue-100 mb-6">Regular checkups and a healthy lifestyle are the keys to a long life.</p>
              <button 
                onClick={() => setActiveTab('checker')}
                className="bg-white text-blue-600 px-6 py-3 rounded-full font-bold hover:bg-blue-50 transition-colors"
              >
                Check Symptoms Now
              </button>
            </div>
          </div>
        )}

        {/* Hospitals Section */}
        {activeTab === 'hospitals' && (
          <div className="max-w-4xl mx-auto">
            <div className="mb-12">
              <h2 className="text-3xl font-bold text-slate-800 mb-4">Find Nearby Hospitals</h2>
              <p className="text-slate-600">Locate medical facilities in your area.</p>
            </div>

            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 mb-8">
              <div className="flex gap-4">
                <div className="flex-1 relative">
                  <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 w-5 h-5" />
                  <input 
                    type="text"
                    placeholder="Enter your village or city name"
                    className="w-full pl-12 pr-4 py-4 rounded-xl border border-slate-200 focus:ring-2 focus:ring-blue-500 outline-none"
                  />
                </div>
                <button className="bg-blue-600 text-white px-8 py-4 rounded-xl font-bold hover:bg-blue-700 transition-colors">
                  Search
                </button>
              </div>
            </div>

            <div className="space-y-4">
              {MOCK_HOSPITALS.map((hospital, i) => (
                <motion.div 
                  key={i}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex flex-col md:flex-row md:items-center justify-between gap-4"
                >
                  <div className="flex gap-4 items-start">
                    <div className="bg-blue-50 p-3 rounded-xl">
                      <MapPin className="text-blue-600 w-6 h-6" />
                    </div>
                    <div>
                      <h3 className="font-bold text-lg text-slate-800">{hospital.name}</h3>
                      <p className="text-slate-500 text-sm flex items-center gap-1">
                        <MapPin className="w-3 h-3" /> {hospital.location}
                      </p>
                    </div>
                  </div>
                  
                  <div className="flex flex-wrap items-center gap-6">
                    <div className="text-right">
                      <p className="text-xs text-slate-400 uppercase font-bold tracking-wider">Distance</p>
                      <p className="font-bold text-slate-700">{hospital.distance}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs text-slate-400 uppercase font-bold tracking-wider">Contact</p>
                      <p className="font-bold text-blue-600 flex items-center gap-1">
                        <Phone className="w-4 h-4" /> {hospital.contact}
                      </p>
                    </div>
                    <button className="bg-slate-100 text-slate-700 px-4 py-2 rounded-lg font-medium hover:bg-slate-200 transition-colors">
                      View Map
                    </button>
                  </div>
                </motion.div>
              ))}
            </div>

            <div className="mt-12 p-6 bg-slate-100 rounded-2xl flex items-center gap-4">
              <Clock className="text-slate-500 w-6 h-6" />
              <p className="text-slate-600 text-sm">
                <strong>Note:</strong> Hospital availability and contact numbers may change. 
                In case of emergency, call 102 or 108 (Emergency Services).
              </p>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="bg-white border-t border-slate-200 py-12 mt-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-4 gap-12">
            <div className="col-span-2">
              <div className="flex items-center gap-2 mb-6">
                <div className="bg-blue-600 p-1.5 rounded-lg">
                  <Stethoscope className="text-white w-5 h-5" />
                </div>
                <span className="font-bold text-xl text-slate-800">AI Health Checker</span>
              </div>
              <p className="text-slate-500 max-w-md leading-relaxed">
                Empowering rural communities with instant health guidance. 
                Our mission is to bridge the gap between technology and healthcare for everyone.
              </p>
            </div>
            <div>
              <h4 className="font-bold text-slate-800 mb-6 uppercase text-sm tracking-widest">Quick Links</h4>
              <ul className="space-y-4">
                {['home', 'checker', 'tips', 'hospitals'].map((tab) => (
                  <li key={tab}>
                    <button 
                      onClick={() => setActiveTab(tab as any)}
                      className="text-slate-500 hover:text-blue-600 transition-colors capitalize"
                    >
                      {tab === 'checker' ? 'Symptom Checker' : tab === 'tips' ? 'Health Tips' : tab}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="font-bold text-slate-800 mb-6 uppercase text-sm tracking-widest">Emergency</h4>
              <ul className="space-y-4">
                <li className="flex items-center gap-2 text-red-600 font-bold">
                  <Phone className="w-4 h-4" /> 108 (Ambulance)
                </li>
                <li className="flex items-center gap-2 text-slate-500">
                  <Phone className="w-4 h-4" /> 102 (Maternal Care)
                </li>
              </ul>
            </div>
          </div>
          <div className="mt-12 pt-8 border-t border-slate-100 text-center text-slate-400 text-sm">
            <p>© {new Date().getFullYear()} AI Health Symptom Checker. All rights reserved.</p>
            <p className="mt-2 text-xs">Built with care for rural health.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
